### ISSUE TITLE
Cambios

### ISSUE THREAD

**Issue by fedm4** [ligiaballesterosf/LoginSemana1#1]
- [x] Los atributos no llevan punto y coma al cerrar la comilla.  O sea ```type="password";``` deberia ser ```type="password"``` sin el ";".
- [x] Borrar los divs porque no son necesarios.
- [x] El width de la clase datos deberia ser de 100%

**Comment by ligiaballesterosf** [comment]
Ya realice los cambios. Muchas gracias, Fede.
